// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aicupper.models;

namespace aicupper.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20181023223153_Started")]
    partial class Started
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aicupper.models.AICupperAccount", b =>
                {
                    b.Property<int>("AICupperCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AICupperAccountID");

                    b.Property<string>("CompanyAddress");

                    b.Property<string>("CompanyName");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhoneNumber");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool?>("IsActive");

                    b.Property<string>("SaltedPassword");

                    b.Property<string>("UserName");

                    b.HasKey("AICupperCustomerID");

                    b.ToTable("AICupperAccounts");
                });

            modelBuilder.Entity("aicupper.models.country", b =>
                {
                    b.Property<string>("CountryCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryName");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("aicupper.models.cuppingEvent", b =>
                {
                    b.Property<int>("CuppingEventID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AICupperAccountAICupperCustomerID");

                    b.Property<Guid>("AICupperAccountID");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventLocation");

                    b.Property<string>("EventNotes");

                    b.Property<int>("NumberOfJudges");

                    b.Property<int>("NumberOfSamples");

                    b.Property<string>("Title");

                    b.HasKey("CuppingEventID");

                    b.HasIndex("AICupperAccountAICupperCustomerID");

                    b.ToTable("CuppingEvents");
                });

            modelBuilder.Entity("aicupper.models.judge", b =>
                {
                    b.Property<int>("JudgeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AICupperAccountAICupperCustomerID");

                    b.Property<Guid>("AICupperAccountID");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("JudgeName")
                        .IsRequired();

                    b.Property<string>("KnownAs");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("JudgeID");

                    b.HasIndex("AICupperAccountAICupperCustomerID");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("aicupper.models.judgeEvent", b =>
                {
                    b.Property<int>("JudgeEventID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AICupperAccountID");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("CuppingEventID");

                    b.Property<bool>("IsEnabled");

                    b.Property<int>("JudgeID");

                    b.HasKey("JudgeEventID");

                    b.HasIndex("JudgeID");

                    b.ToTable("JudgeCuppingEvents");
                });

            modelBuilder.Entity("aicupper.models.cuppingEvent", b =>
                {
                    b.HasOne("aicupper.models.AICupperAccount")
                        .WithMany("CuppingEvents")
                        .HasForeignKey("AICupperAccountAICupperCustomerID");
                });

            modelBuilder.Entity("aicupper.models.judge", b =>
                {
                    b.HasOne("aicupper.models.AICupperAccount")
                        .WithMany("Judges")
                        .HasForeignKey("AICupperAccountAICupperCustomerID");
                });

            modelBuilder.Entity("aicupper.models.judgeEvent", b =>
                {
                    b.HasOne("aicupper.models.judge")
                        .WithMany("CuppingEvents")
                        .HasForeignKey("JudgeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
