// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aicupper.models;

namespace aicupper.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20181020182710_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aicupper.models.cuppingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CuppingEventID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AICupperAccountID");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventLocation");

                    b.Property<string>("EventNotes");

                    b.Property<int>("NumberOfJudges");

                    b.Property<int>("NumberOfSamples");

                    b.Property<string>("Title");

                    b.Property<string>("judgeId");

                    b.HasKey("Id");

                    b.HasIndex("judgeId");

                    b.ToTable("CuppingEvents");
                });

            modelBuilder.Entity("aicupper.models.judge", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("JudgeID");

                    b.Property<Guid>("AICupperAccountID");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("JudgeName")
                        .IsRequired();

                    b.Property<string>("KnownAs");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("aicupper.models.cuppingEvent", b =>
                {
                    b.HasOne("aicupper.models.judge")
                        .WithMany("CuppingEvents")
                        .HasForeignKey("judgeId");
                });
#pragma warning restore 612, 618
        }
    }
}
